version: '3'
services:
  web:
    image: nba-player-stats
    deploy:
      replicas: 2
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/testDB
      SPRING_DATASOURCE_USERNAME: testUser
      SPRING_DATASOURCE_PASSWORD: testPassword

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web